# Generated by Django 5.1.1 on 2024-09-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSecondLayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_id', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('object_id', models.IntegerField()),
                ('perm_type', models.CharField(choices=[('A', 'add'), ('D', 'delete'), ('E', 'edit'), ('R', 'read')], default='R', max_length=2)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='contenttypes.contenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'perm_type'), name='unique permission')],
            },
        ),
    ]
