# Generated by Django 5.1.1 on 2024-10-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('perms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoPointFiveRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_detail', models.CharField(max_length=250)),
                ('function_id', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('perm_type', models.CharField(choices=[('A', 'add'), ('D', 'delete'), ('E', 'edit'), ('R', 'read')], default='R', max_length=2)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_registries', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionTwoPointFiveLayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_point_five', to='perms.permissionsecondlayermodel')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_model', to='perms.twopointfiveregistry')),
            ],
        ),
    ]
