# Generated by Django 5.1.1 on 2025-06-09 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyzworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="submission",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="last_name",
        ),
        migrations.AddField(
            model_name="folderupload",
            name="assignment_mode",
            field=models.CharField(
                choices=[
                    ("device", "Device Only"),
                    ("link", "Link Only"),
                    ("both", "Both"),
                ],
                default="both",
                help_text="Allow students to submit via device, link, or both",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="exchange_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Server-generated link ID (if mode=link)",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submission_mode",
            field=models.CharField(
                choices=[("device", "Device"), ("link", "Link")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="Client device UUID (if mode=device)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="wyzworks.device",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submission_mode", "device")),
                fields=("folder", "device"),
                name="unique_folder_device",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("submission_mode", "Link")),
                fields=("folder", "exchange_uuid"),
                name="unique_folder_exchange",
            ),
        ),
    ]
