# Generated by Django 5.1.1 on 2025-06-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyzworks", "0003_folderupload_editor_states_submission_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folderupload",
            name="drag_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="folderupload",
            name="drag_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="folderupload",
            name="prev_h",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="folderupload",
            name="prev_w",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="folderupload",
            name="prev_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="folderupload",
            name="prev_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
