# Generated by Django 5.1.1 on 2025-06-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyzworks", "0004_folderupload_drag_x_folderupload_drag_y_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manage_token",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "access_token",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_fields",
                        to="wyzworks.form",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
