# Generated by Django 5.1.1 on 2025-06-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyzworks", "0005_form_completedfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedfield",
            name="default_props",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="completedfield",
            name="field_type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="completedfield",
            name="uid",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="completedfield",
            name="validation",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
