# Generated by Django 5.1.1 on 2025-06-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyzworks", "0007_completedfield_gradable_completedfield_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_id",
                    models.CharField(
                        help_text="UUID or other identifier from the frontend",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="wyzworks.form",
                    ),
                ),
            ],
            options={
                "unique_together": {("form", "file_id")},
            },
        ),
    ]
