# Generated by Django 5.1.1 on 2025-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_link",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("M", "Manager"), ("N", "User")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("file_path", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
