# Generated by Django 5.1.1 on 2025-04-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoupload",
            name="login_required",
            field=models.BooleanField(
                default=False,
                help_text="Determined by scanning the URL for login restrictions.",
            ),
        ),
        migrations.AddField(
            model_name="videoupload",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="The URL of the source page.",
                max_length=2048,
                null=True,
            ),
        ),
    ]
