# Generated by Django 5.1.1 on 2025-04-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0002_videoupload_login_required_videoupload_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.BigIntegerField()),
                ("end_time", models.BigIntegerField()),
                ("thumb_start", models.TextField()),
                ("thumb_end", models.TextField()),
                ("events", models.JSONField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "trimmed_video",
                    models.CharField(
                        blank=True,
                        help_text="Stores the URL or key for the trimmed video clip.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="videoupload",
            name="steps",
            field=models.ManyToManyField(
                blank=True, related_name="video_uploads", to="screener.step"
            ),
        ),
    ]
