# Generated by Django 5.1.1 on 2025-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0003_step_videoupload_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
