# Generated by Django 5.1.1 on 2025-05-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0004_step_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoupload",
            name="user_type",
        ),
        migrations.AddField(
            model_name="videoupload",
            name="shareable_link",
            field=models.CharField(
                blank=True,
                help_text="A second UUID used for sharing with others.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
