# Generated by Django 5.1.1 on 2025-05-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0005_remove_videoupload_user_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoupload",
            name="recordings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
