# Generated by Django 5.1.1 on 2024-09-30 12:24

import actions.response
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import perms.utilities
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(perms.utilities.ParentPriorityGenerator, models.Model),
        ),
        migrations.CreateModel(
            name='DummyPerm2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(perms.utilities.ParentPriorityGenerator, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+1111111111', max_length=128, region=None)),
            ],
            bases=(perms.utilities.ParentPriorityGenerator, models.Model),
        ),
        migrations.CreateModel(
            name='OrgSignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'signees',
                'default_related_name': 'signees',
            },
            bases=(actions.response.ActionResponse, models.Model),
        ),
        migrations.CreateModel(
            name='AssignedPermsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_retainer', to='organizations.organizationuser')),
            ],
        ),
    ]
