# Generated by Django 5.1.1 on 2024-09-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_alter_organization_slug'),
        ('orgs', '0001_initial'),
        ('perms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedpermsmodel',
            name='permmissions',
            field=models.ManyToManyField(related_name='allowed_users', to='perms.permissionsecondlayermodel'),
        ),
        migrations.AddField(
            model_name='dummyperm',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dum', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='dummyperm2',
            name='permss',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dum2', to='orgs.dummyperm'),
        ),
        migrations.AddField(
            model_name='organizationextension',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationextension',
            name='parent_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_orgs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='orgsignees',
            name='admin_approve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgsignees',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='orgsignees',
            name='signee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_ups_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
