# Generated by Django 5.1.1 on 2024-10-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_initial'),
        ('perms', '0002_twopointfiveregistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedpermsmodel',
            name='functional_permissions',
            field=models.ManyToManyField(related_name='functional_users', to='perms.permissiontwopointfivelayermodel'),
        ),
    ]
