# Generated by Django 5.1.1 on 2024-11-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_assignedpermsmodel_functional_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedpermsmodel',
            name='stack_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
