# Generated by Django 5.1.1 on 2024-09-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0007_alter_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField()),
                ('record_type', models.CharField(choices=[('C', 'Create'), ('E', 'Change'), ('D', 'Delete'), ('T', 'Took'), ('S', 'Sent'), ('Q', 'Requested'), ('A', 'Accepted'), ('L', 'Declined'), ('R', 'Responded')], default='C', max_length=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_class_records', to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.IntegerField()),
                ('record_type', models.CharField(choices=[('C', 'Create'), ('E', 'Change'), ('D', 'Delete'), ('T', 'Took'), ('S', 'Sent'), ('Q', 'Requested'), ('A', 'Accepted'), ('L', 'Declined'), ('R', 'Responded')], default='C', max_length=1)),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_actions', to='organizations.organization')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_class_records', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('responded', models.BooleanField()),
                ('response_type', models.CharField(choices=[('O', 'Organization'), ('U', 'User')], default='U', max_length=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='contenttypes.contenttype')),
                ('linker', models.ManyToManyField(related_name='linked_response', to='actions.personalrecord')),
                ('users', models.ManyToManyField(related_name='need_to_respond', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
