# Generated by Django 5.1.1 on 2025-03-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("C", "Create"),
                    ("E", "Change"),
                    ("D", "Delete"),
                    ("T", "Took"),
                    ("S", "Sent"),
                    ("Q", "Requested"),
                    ("A", "Accepted"),
                    ("L", "Declined"),
                    ("R", "Responded"),
                    ("B", "Added"),
                    ("M", "Remove"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="personalrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("C", "Create"),
                    ("E", "Change"),
                    ("D", "Delete"),
                    ("T", "Took"),
                    ("S", "Sent"),
                    ("Q", "Requested"),
                    ("A", "Accepted"),
                    ("L", "Declined"),
                    ("R", "Responded"),
                    ("B", "Added"),
                    ("M", "Remove"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
