# Generated by Django 5.1.1 on 2024-09-30 12:24

import django.db.models.deletion
import perms.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0007_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_provided_services', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, perms.utilities.ParentPriorityGenerator),
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_provided_services', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, perms.utilities.ParentPriorityGenerator),
        ),
        migrations.CreateModel(
            name='Enviromental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_provided_services', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, perms.utilities.ParentPriorityGenerator),
        ),
        migrations.CreateModel(
            name='Floater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_provided_services', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, perms.utilities.ParentPriorityGenerator),
        ),
        migrations.CreateModel(
            name='ServicesContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.SlugField(blank=True, max_length=250, null=True)),
                ('object_id', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='contenttypes.contenttype')),
            ],
        ),
    ]
