# Generated by Django 5.1.1 on 2024-09-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attr_Dependecies_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=30)),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependers', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAbstractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
                ('dependecies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent', to='contenttypes.contenttype')),
                ('resolutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolves', to='contenttypes.contenttype')),
                ('responsibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permed_model', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to='task.taskabstractmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved', models.BooleanField()),
                ('users', models.ManyToManyField(related_name='task_do', to=settings.AUTH_USER_MODEL)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='task.taskmodel')),
            ],
        ),
    ]
