# Generated by Django 5.1.1 on 2025-05-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_id",
                    models.PositiveIntegerField(
                        help_text="Original question identifier"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject name, e.g. Math", max_length=100
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Main topic, e.g. Fractions basics", max_length=200
                    ),
                ),
                (
                    "subtopic",
                    models.CharField(
                        blank=True, help_text="Subtopic or detail hint", max_length=200
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        help_text="Grade level between 1 and 12"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        help_text="Question type, e.g. Short Answer, Word Problem",
                        max_length=50,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The text of the question"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        help_text="Difficulty rating",
                        max_length=10,
                    ),
                ),
                (
                    "rubric_part_1",
                    models.TextField(blank=True, help_text="First rubric criterion"),
                ),
                (
                    "rubric_part_2",
                    models.TextField(blank=True, help_text="Second rubric criterion"),
                ),
                (
                    "rubric_part_3",
                    models.TextField(blank=True, help_text="Third rubric criterion"),
                ),
                (
                    "rubric_part_4",
                    models.TextField(blank=True, help_text="Fourth rubric criterion"),
                ),
                (
                    "rubric_part_5",
                    models.TextField(blank=True, help_text="Fifth rubric criterion"),
                ),
                (
                    "jsx_code",
                    models.TextField(
                        blank=True, help_text="JSXGraph code snippet, if any"
                    ),
                ),
                (
                    "mathjax",
                    models.TextField(
                        blank=True, help_text="LaTeX representation of the question"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Generated Question",
                "verbose_name_plural": "Generated Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptDSL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The original text prompt sent to the OpenAI API"
                    ),
                ),
                (
                    "dsl",
                    models.JSONField(
                        help_text="The Fabric.js–ready DSL output, stored as raw JSON"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prompt + DSL Record",
                "verbose_name_plural": "Prompt + DSL Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
