# Generated by Django 5.1.1 on 2025-06-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RubricRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        help_text="User’s raw rubric prompt or existing rubric text"
                    ),
                ),
                (
                    "generated_rubric",
                    models.JSONField(
                        blank=True,
                        help_text="The list of {part, weight} dicts returned by GPT",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
