# Generated by Django 5.1.1 on 2024-09-30 12:24

import actions.response
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_alter_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecieverRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecieverServiceProvide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reciever', models.BooleanField()),
            ],
            options={
                'db_table': 'reciever_service_retainer',
            },
        ),
        migrations.CreateModel(
            name='RecieverSignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reciever_signee',
                'default_related_name': 'reciever_signee',
            },
            bases=(actions.response.ActionResponse, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceReciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecieverRefactored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OverwatchSignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, null=True)),
                ('admin_approve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_aproving', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_signees', to='organizations.organization')),
                ('signee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'overwatcher_signee',
                'default_related_name': 'overwatcher_signee',
            },
            bases=(actions.response.ActionResponse, models.Model),
        ),
        migrations.CreateModel(
            name='ProviderServiceProvide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_retainer', to='organizations.organizationuser')),
            ],
            options={
                'db_table': 'org_user_service_retainer',
            },
        ),
    ]
