# Generated by Django 5.1.1 on 2024-09-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('wyz_address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attn',
            name='login_location',
            field=models.ManyToManyField(related_name='logger', to='wyz_address.wyzaddress'),
        ),
        migrations.AddField(
            model_name='attn',
            name='users',
            field=models.ManyToManyField(related_name='needed_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='login',
            name='attended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_logs', to='attendance.attn'),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to=settings.AUTH_USER_MODEL),
        ),
    ]
