# Generated by Django 5.1.1 on 2025-03-14 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FolderUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("folder_name", models.CharField(max_length=255)),
                ("unique_link", models.SlugField(blank=True, unique=True)),
                (
                    "file_path",
                    models.CharField(
                        help_text="The location on disk (or S3, etc.) where the folder is stored.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
