# Generated by Django 5.1.1 on 2025-03-23 01:57

import django.db.models.deletion
import works.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeEditorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tabs_orientation",
                    models.CharField(default="horizontal", max_length=20),
                ),
                ("open_menu", models.CharField(blank=True, max_length=50, null=True)),
                ("language", models.IntegerField(default=0)),
                ("preview_modal", models.BooleanField(default=False)),
                ("selected_editor", models.IntegerField(default=0)),
                ("selected_item", models.JSONField(blank=True, null=True)),
                (
                    "active_component",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("z_indices", models.JSONField(default=works.models.default_z_indices)),
                (
                    "folder_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_editor_state",
                        to="works.folderupload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeEntryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("editor_id", models.IntegerField()),
                ("language", models.CharField(default="html", max_length=50)),
                (
                    "code",
                    models.TextField(
                        default="<h1>Hello, World!</h1>\n<p>This is an HTML editor.</p>"
                    ),
                ),
                ("path_to", models.CharField(blank=True, max_length=500)),
                ("show_lines", models.BooleanField(default=True)),
                ("selected_language", models.CharField(default="html", max_length=50)),
                ("size", models.JSONField(default=works.models.default_size)),
                ("font_size", models.IntegerField(default=14)),
                ("tab_state", models.JSONField(default=works.models.default_tab_state)),
                ("scroll_top", models.IntegerField(default=0)),
                ("position", models.JSONField(default=works.models.default_position)),
                (
                    "active_handle",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "code_editor_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_entries",
                        to="works.codeeditorstate",
                    ),
                ),
            ],
            options={
                "ordering": ["editor_id"],
                "unique_together": {("code_editor_state", "editor_id")},
            },
        ),
    ]
